name: Hello world
on: workflow_dispatch
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "hello world"
  A:
    needs: hello-world-job
    runs-on: ubuntu-latest

    steps:
      - name: Run job A
        run: echo "Job A executed"

  B:
    needs: hello-world-job
    runs-on: ubuntu-latest

    steps:
      - name: Run job B
        run: echo "Job B executed"
