name: Hello world
on:  
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run a one-line script
        run: echo "hello world"
  A:
    needs: hello-world-job
    runs-on: ubuntu-latest
    steps:
      - name: Run job A
        run: echo "Job A executed"
  B:
    needs: hello-world-job
    runs-on: ubuntu-latest
    steps:
      - name: Run job B
        run: echo "Job B executed"
