name: Hello world
on:
  schedule:
    - cron: '*/5 * * * *'
      timezone: "Europe/Lisbon"
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "hello world"
  A:
    needs: hello-world-job
    runs-on: ubuntu-latest
    steps:
      - name: Run job A
        run: echo "Job A executed"
  B:
    needs: hello-world-job
    runs-on: ubuntu-latest
    steps:
      - name: Run job B
        run: echo "Job B executed"
